/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionpharmacie;

import com.tmbd.pharmacie.*;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author MT98
 */
public class AdministrateurPharmacie extends javax.swing.JFrame {
TmbdRequests reqStat = new TmbdRequests("pharmacie_db");
TmbdRequests reqDyn;
private int nbAcha = 0;
public String nomPharma="";
public String idGerant = "";
public String opera="";
public String fourniStock = "";
private String idAcha = "";





    /**
     * Creates new form AdministrateurPharmacie
     */
    public AdministrateurPharmacie() {
        initComponents();
        panelFamille.setVisible(false);
        panelMedicament.setVisible(false);
        
        
        panAjouEmp.setVisible(false);
        panAjouFrs.setVisible(false);
        panelEntite.setVisible(false);
        jPanel1.setVisible(false);
    }

    public AdministrateurPharmacie(String login, String pwd, String phNam) {
        initComponents();
        nomPharma = phNam;
        loginConnecter = login;
        idGerant = login;
        pwdConnecter = pwd;
        panelFamille.setVisible(false);
        panelMedicament.setVisible(false);
        
        
        panAjouEmp.setVisible(false);
        panAjouFrs.setVisible(false);
        panelEntite.setVisible(false);
        jPanel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAdminPharm = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelAjouterMenu = new javax.swing.JLabel();
        labelModifierMenu = new javax.swing.JLabel();
        labelSupprimerMenu = new javax.swing.JLabel();
        labelStatistiqueMenu = new javax.swing.JLabel();
        labelDeconnecterMenu = new javax.swing.JLabel();
        labelLogoMenu = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        panelEntite = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelMedicament = new javax.swing.JLabel();
        labelFamille = new javax.swing.JLabel();
        panelFamille = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        panAjouFrs = new javax.swing.JPanel();
        tPren1 = new javax.swing.JTextField();
        Prenom1 = new javax.swing.JLabel();
        tTel1 = new javax.swing.JTextField();
        tel1 = new javax.swing.JLabel();
        nom1 = new javax.swing.JLabel();
        tnom1 = new javax.swing.JTextField();
        tMail1 = new javax.swing.JTextField();
        Prenom3 = new javax.swing.JLabel();
        bRetour2 = new javax.swing.JButton();
        bValid2 = new javax.swing.JButton();
        panelMedicament = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        combFrs = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        combMedi = new javax.swing.JComboBox<>();
        quantite = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        LabDateExp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        labPau = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        retour = new javax.swing.JButton();
        assigner = new javax.swing.JButton();
        panAjouEmp = new javax.swing.JPanel();
        Prenom = new javax.swing.JLabel();
        tPren = new javax.swing.JTextField();
        tnom = new javax.swing.JTextField();
        nom = new javax.swing.JLabel();
        tTel = new javax.swing.JTextField();
        tel = new javax.swing.JLabel();
        Prenom2 = new javax.swing.JLabel();
        tMail = new javax.swing.JTextField();
        bRetour1 = new javax.swing.JButton();
        bValid1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAdminPharm.setBackground(new java.awt.Color(204, 204, 204));
        panelAdminPharm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setBackground(new java.awt.Color(255, 255, 255));
        panelMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelMenuMouseEntered(evt);
            }
        });
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionpharmacie/menuAdminPharm.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        panelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 15, 270, 50));

        labelAjouterMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionpharmacie/ajouterMenu.png"))); // NOI18N
        labelAjouterMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAjouterMenuMouseClicked(evt);
            }
        });
        panelMenu.add(labelAjouterMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 260, 30));

        labelModifierMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionpharmacie/modifierMenu.png"))); // NOI18N
        labelModifierMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelModifierMenuMouseClicked(evt);
            }
        });
        panelMenu.add(labelModifierMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 260, 30));

        labelSupprimerMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionpharmacie/supprimerMenu.png"))); // NOI18N
        labelSupprimerMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSupprimerMenuMouseClicked(evt);
            }
        });
        panelMenu.add(labelSupprimerMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 260, 30));

        labelStatistiqueMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionpharmacie/statisqueMenu.png"))); // NOI18N
        panelMenu.add(labelStatistiqueMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 260, 30));

        labelDeconnecterMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionpharmacie/deconnecterMenu.png"))); // NOI18N
        labelDeconnecterMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDeconnecterMenuMouseClicked(evt);
            }
        });
        panelMenu.add(labelDeconnecterMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 260, 30));

        labelLogoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionpharmacie/phar.png"))); // NOI18N
        panelMenu.add(labelLogoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 162, 120));

        panelAdminPharm.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 300, 650));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelEntite.setBackground(new java.awt.Color(0, 204, 204));
        panelEntite.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionpharmacie/stock.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        panelEntite.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionpharmacie/fournisseur.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        panelEntite.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 130, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionpharmacie/employe.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        panelEntite.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 130, 40));

        labelMedicament.setBackground(new java.awt.Color(0, 153, 153));
        labelMedicament.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelMedicament.setForeground(new java.awt.Color(255, 255, 255));
        labelMedicament.setText("Medicament");
        labelMedicament.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMedicamentMouseClicked(evt);
            }
        });
        panelEntite.add(labelMedicament, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 110, 30));

        labelFamille.setBackground(new java.awt.Color(0, 204, 204));
        labelFamille.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelFamille.setForeground(new java.awt.Color(255, 255, 255));
        labelFamille.setText("Famille");
        labelFamille.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelFamilleMouseClicked(evt);
            }
        });
        panelEntite.add(labelFamille, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 100, -1));

        jPanel3.add(panelEntite, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 130, 200));

        panelFamille.setBackground(new java.awt.Color(0, 204, 204));
        panelFamille.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setText("jTextField1");
        panelFamille.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 110, -1));

        jButton1.setText("jButton1");
        panelFamille.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelFamille.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 150, -1));

        jButton2.setText("jButton2");
        panelFamille.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        panelFamille.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 530, 190));

        jButton3.setText("jButton3");
        panelFamille.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, -1));

        jPanel3.add(panelFamille, new org.netbeans.lib.awtextra.AbsoluteConstraints(2000, 50, 840, 560));

        panAjouFrs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panAjouFrs.add(tPren1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 130, 30));

        Prenom1.setText("prenom");
        panAjouFrs.add(Prenom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        tTel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTel1ActionPerformed(evt);
            }
        });
        panAjouFrs.add(tTel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 130, 30));

        tel1.setText("telephone");
        panAjouFrs.add(tel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, 20));

        nom1.setText("nom");
        panAjouFrs.add(nom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 70, 20));
        panAjouFrs.add(tnom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 130, 30));
        panAjouFrs.add(tMail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 130, 30));

        Prenom3.setText("email");
        panAjouFrs.add(Prenom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 70, 20));

        bRetour2.setText("Retour");
        bRetour2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bRetour2MouseClicked(evt);
            }
        });
        panAjouFrs.add(bRetour2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        bValid2.setText("Valider");
        bValid2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bValid2MouseClicked(evt);
            }
        });
        panAjouFrs.add(bValid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        jPanel3.add(panAjouFrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 290, 230));

        panelMedicament.setBackground(new java.awt.Color(0, 204, 204));
        panelMedicament.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setText("jTextField2");
        panelMedicament.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelMedicament.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        jTextField3.setText("jTextField3");
        panelMedicament.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        jTextField4.setText("jTextField4");
        panelMedicament.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jTextField5.setText("jTextField5");
        panelMedicament.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        jButton4.setText("jButton4");
        panelMedicament.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        panelMedicament.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 490, 190));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelMedicament.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        jButton5.setText("jButton5");
        panelMedicament.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, -1, -1));

        jButton6.setText("jButton6");
        panelMedicament.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, -1, -1));

        jPanel3.add(panelMedicament, new org.netbeans.lib.awtextra.AbsoluteConstraints(2000, 70, 800, 500));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nom Fournisseur");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        combFrs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(combFrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 250, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nom Médicament");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        combMedi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(combMedi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 250, 30));
        jPanel1.add(quantite, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 60, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Quantité");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));
        jPanel1.add(LabDateExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 250, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Date d'expiration jj-mm-aaaa");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));
        jPanel1.add(labPau, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 270, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("prix d'achat unitaire");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        jButton7.setText("Ajouter");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 110, -1));

        retour.setText("Retour");
        retour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retourMouseClicked(evt);
            }
        });
        jPanel1.add(retour, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 100, -1));

        assigner.setText("assigner");
        assigner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assignerMouseClicked(evt);
            }
        });
        jPanel1.add(assigner, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 640, 430));

        panAjouEmp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Prenom.setText("prenom");
        panAjouEmp.add(Prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 70, 20));
        panAjouEmp.add(tPren, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 130, 30));
        panAjouEmp.add(tnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 140, 30));

        nom.setText("nom");
        panAjouEmp.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 70, 20));
        panAjouEmp.add(tTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 130, 30));

        tel.setText("telephone");
        panAjouEmp.add(tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 70, 20));

        Prenom2.setText("email");
        panAjouEmp.add(Prenom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 70, 20));
        panAjouEmp.add(tMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 130, 30));

        bRetour1.setText("Retour");
        bRetour1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bRetour1MouseClicked(evt);
            }
        });
        panAjouEmp.add(bRetour1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        bValid1.setText("Valider");
        bValid1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bValid1MouseClicked(evt);
            }
        });
        panAjouEmp.add(bValid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        jPanel3.add(panAjouEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 400, 240));

        panelAdminPharm.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 1010, 650));

        getContentPane().add(panelAdminPharm, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 1380, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelMedicamentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMedicamentMouseClicked
        // TODO add your handling code here:
        panelMedicament.setVisible(true);
        panelFamille.setVisible(false);
    }//GEN-LAST:event_labelMedicamentMouseClicked

    private void labelFamilleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFamilleMouseClicked
        // TODO add your handling code here:
        panelMedicament.setVisible(false);
        panelFamille.setVisible(true);
    }//GEN-LAST:event_labelFamilleMouseClicked

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained
        try {
            ResultSet frs = reqDyn.queryAllFrs();
            while(frs.next()){
                combFrs.addItem(frs.getString("id")+" : "+frs.getString("prenom")+" "+frs.getString("nom"));
            }
        } catch (Exception ex) {
            Logger.getLogger(AdministrateurPharmacie.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jPanel1FocusGained

    private void assignerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assignerMouseClicked
        combFrs.setVisible(false);
        assigner.setVisible(false);
        jLabel2.setVisible(false);
        fourniStock = combFrs.getSelectedItem().toString();
        nbAcha = 0;
        
        jButton7.setVisible(true);
    }//GEN-LAST:event_assignerMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        
        try {
            System.out.println(nomPharma);
            //nomPharma=reqStat.queryPharmaGerant(idGerant).getString("nom");
            reqDyn = new TmbdRequests("pharmacie_"+nomPharma);
        } catch (Exception ex) {
            Logger.getLogger(AdministrateurPharmacie.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowActivated

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked

        TmbdRequests tmbReq = new TmbdRequests("pharmacie_"+nomPharma);
        try {
            String[] parti = LabDateExp.getText().split("-");
            System.out.println(parti[0]);
            System.out.println(parti[1]);
            System.out.println(parti[2]);
            
            if(parti.length==3){
                System.out.println("okokokokoko");
            boolean ok = false;
            
            
            if(nbAcha<=0){
                idAcha = tmbReq.generId("achat_t");
                System.out.println("id-> "+idAcha);
                String idFrs = combFrs.getSelectedItem().toString().split(" : ")[0];
                Date dat = tmbReq.getMyDate();
                ok = tmbReq.insertAchat(idAcha, dat, idFrs);
            }
            if( (ok) || ((!ok)&&(nbAcha!=0)) ){
            
            nbAcha++;
                
                Date datExp = new Date(Integer.valueOf(parti[2]), Integer.valueOf(parti[1]), Integer.valueOf(parti[0]));
                TmbdRequests reqStok1 = new TmbdRequests("pharmacie_"+nomPharma);
                System.out.println(combMedi.getSelectedItem().toString()+"////");
                System.out.println("bf-> "+idAcha);
                ok = reqStok1.insertAchatMedicament(combMedi.getSelectedItem().toString(),idAcha , Integer.valueOf(labPau.getText()),datExp , Float.valueOf(labPau.getText()));
                
                if(ok){
                
                int option = JOptionPane.showConfirmDialog(null, "Achat enregistré avec succès. Voulez-vous ajouter un autre médicament ?",
                                                "Ajout d'un nouveau medicament",
                                                JOptionPane.YES_NO_OPTION,
                                                JOptionPane.QUESTION_MESSAGE);
                if (option == JOptionPane.OK_OPTION){
                    LabDateExp.setText("");
                    labPau.setText("");
                    jPanel1.setVisible(true);
                    String mediChoisi = combMedi.getSelectedItem().toString();
                    combMedi.removeItem(mediChoisi);
                }
               else {
                    jPanel1.hide();
                }
                
                }
                else JOptionPane.showMessageDialog(null, "UNE ERREUR S'EST PRODUITE");
            }    
            }
            else JOptionPane.showMessageDialog(null, "Format de date non valide");
         } catch (Exception ex) {
         Logger.getLogger(AdministrateurPharmacie.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton7MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

        combFrs.setVisible(true);
        assigner.setVisible(true);
        jLabel2.setVisible(true);
        
        jButton7.setVisible(false);
        
        if(opera.equals("ajouter")){
              jPanel1.setVisible(true);
              
              combMedi.removeAllItems();
              combFrs.removeAllItems();
        try {
            TmbdRequests reqStok = new TmbdRequests("pharmacie_"+nomPharma);
            System.out.println("pharmacie_"+nomPharma);
            ResultSet listMedic = reqStok.queryAllMedicaments();
            ListeFonctions lf = new ListeFonctions();
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            model = lf.chargerComboSingle(listMedic,"nom");
            combMedi.setModel(model);
            /*while(pharms.next()){
                lispharma.addItem(pharms.getString("nom"));
            }*/
        } catch (Exception ex) {
            Logger.getLogger(AdministrateurPharmacie.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            TmbdRequests reqStok = new TmbdRequests("pharmacie_"+nomPharma);
            ResultSet listFrs = reqStok.queryAllFrs();
           /** ListeFonctions lf = new ListeFonctions();
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            model = lf.chargerComboSingle(listFrs,"nom");
            combFrs.setModel(model);
            * */
            while(listFrs.next()){
                combFrs.addItem(listFrs.getString("id")+" : "+listFrs.getString("prenom")+" "+listFrs.getString("prenom"));
            }
        } catch (Exception ex) {
            Logger.getLogger(AdministrateurPharmacie.class.getName()).log(Level.SEVERE, null, ex);
        }
              
              
              
          }
          
          
    }//GEN-LAST:event_jLabel3MouseClicked

    private void retourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourMouseClicked
        jPanel1.hide();
    }//GEN-LAST:event_retourMouseClicked

    private void bRetour1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bRetour1MouseClicked
        tPren.setText("");
        tMail.setText("");
        tel.setText("");
        tnom.setText("");
        panAjouEmp.setVisible(false);
    }//GEN-LAST:event_bRetour1MouseClicked

    private void bValid1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bValid1MouseClicked
        TmbdRequests ajou = new TmbdRequests("pharmacie_"+this.nomPharma);
        String idEmp = "emp-"+(Math.random()%50);
        String pwdEmp = "emp-"+(Math.random()%50);
        try {
            boolean ok = ajou.insertEmployer(idEmp, pwdEmp, tPren.getText(), tnom.getText(), tel.getText(), tMail.getText());
            if(ok){
                JOptionPane.showMessageDialog(null, "Ajout reussit identifiant : "+idEmp+" mot de passe : "+pwdEmp);
            }else JOptionPane.showMessageDialog(null, "Ne peux pas ajouter cet employe");
        } catch (Exception ex) {
            Logger.getLogger(AdministrateurPharmacie.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bValid1MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        if(opera.equals("ajouter")){
            panAjouEmp.setVisible(true);
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void labelAjouterMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAjouterMenuMouseClicked
        opera = "ajouter";
        panelEntite.setVisible(true);
    }//GEN-LAST:event_labelAjouterMenuMouseClicked

    private void labelModifierMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModifierMenuMouseClicked
        opera = "modifier";
    }//GEN-LAST:event_labelModifierMenuMouseClicked

    private void labelSupprimerMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSupprimerMenuMouseClicked
        opera = "suprimer";
    }//GEN-LAST:event_labelSupprimerMenuMouseClicked

    private void labelDeconnecterMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDeconnecterMenuMouseClicked
        this.hide();
        Accueil ac = new Accueil();
        ac.show();
    }//GEN-LAST:event_labelDeconnecterMenuMouseClicked

    private void bRetour2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bRetour2MouseClicked
        tPren1.setText("");
        tMail1.setText("");
        tel1.setText("");
        tnom1.setText("");
        panAjouFrs.hide();
    }//GEN-LAST:event_bRetour2MouseClicked

    private void bValid2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bValid2MouseClicked
        TmbdRequests ajou = new TmbdRequests("pharmacie_"+this.nomPharma);
        String idFrs = "frs"+(Math.random()%50);
        try {
            boolean ok = ajou.insertFrs(idFrs, tPren1.getText(), tnom1.getText(), tel1.getText(), tMail1.getText());
            if(ok){
                JOptionPane.showMessageDialog(null, "Ajout reussit voici l'identifiant du fournisseur : "+idFrs);
            }else JOptionPane.showMessageDialog(null, "Ne peux pas ajouter ce fournisseur");
        } catch (Exception ex) {
            Logger.getLogger(AdministrateurPharmacie.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bValid2MouseClicked

    private void tTel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTel1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        if(opera.equals("ajouter")){
            panAjouFrs.setVisible(true);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseExited

    private void panelMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelMenuMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrateurPharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrateurPharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrateurPharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrateurPharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministrateurPharmacie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LabDateExp;
    public javax.swing.JLabel Prenom;
    public javax.swing.JLabel Prenom1;
    public javax.swing.JLabel Prenom2;
    public javax.swing.JLabel Prenom3;
    private javax.swing.JButton assigner;
    private javax.swing.JButton bRetour1;
    private javax.swing.JButton bRetour2;
    private javax.swing.JButton bValid1;
    private javax.swing.JButton bValid2;
    private javax.swing.JComboBox<String> combFrs;
    private javax.swing.JComboBox<String> combMedi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField labPau;
    private javax.swing.JLabel labelAjouterMenu;
    private javax.swing.JLabel labelDeconnecterMenu;
    private javax.swing.JLabel labelFamille;
    private javax.swing.JLabel labelLogoMenu;
    private javax.swing.JLabel labelMedicament;
    private javax.swing.JLabel labelModifierMenu;
    private javax.swing.JLabel labelStatistiqueMenu;
    private javax.swing.JLabel labelSupprimerMenu;
    public javax.swing.JLabel nom;
    public javax.swing.JLabel nom1;
    private javax.swing.JPanel panAjouEmp;
    private javax.swing.JPanel panAjouFrs;
    private javax.swing.JPanel panelAdminPharm;
    private javax.swing.JPanel panelEntite;
    private javax.swing.JPanel panelFamille;
    private javax.swing.JPanel panelMedicament;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JSpinner quantite;
    private javax.swing.JButton retour;
    private javax.swing.JTextField tMail;
    private javax.swing.JTextField tMail1;
    private javax.swing.JTextField tPren;
    private javax.swing.JTextField tPren1;
    private javax.swing.JTextField tTel;
    private javax.swing.JTextField tTel1;
    public javax.swing.JLabel tel;
    public javax.swing.JLabel tel1;
    private javax.swing.JTextField tnom;
    private javax.swing.JTextField tnom1;
    // End of variables declaration//GEN-END:variables
    private String loginConnecter;
    private String pwdConnecter;
}
