/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionpharmacie;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author MT98
 */
public class AdministrateurGeneral extends javax.swing.JFrame {

    /**
     * Creates new form AdministrateurGeneral
     */
    public AdministrateurGeneral() {
        initComponents();
        textNom.setVisible(false);
        textAdresse.setVisible(false);
        textNomGer.setVisible(false);
        textPrenomGer.setVisible(false);
        textNumero.setVisible(false);
        textEmail.setVisible(false);
        panelAjouter.setVisible(false);
        panelModifier.setVisible(false);
        panelSupprimer.setVisible(false);
    }

    public AdministrateurGeneral(String login, String pwd) {
        initComponents();
        loginConnecter = login;
        pwdConnecter = pwd;
        textNom.setVisible(false);
        textAdresse.setVisible(false);
        textNomGer.setVisible(false);
        textPrenomGer.setVisible(false);
        textNumero.setVisible(false);
        textEmail.setVisible(false);
        panelAjouter.setVisible(false);
        panelModifier.setVisible(false);
        panelSupprimer.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAdminGeneral = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        labelLogoPharm = new javax.swing.JLabel();
        labelAjoutPharm = new javax.swing.JLabel();
        labelModifPharm = new javax.swing.JLabel();
        labelSupPharm = new javax.swing.JLabel();
        labelDeconPharm = new javax.swing.JLabel();
        labelConteneur = new javax.swing.JLabel();
        panelConsultation = new javax.swing.JPanel();
        textRechercher = new javax.swing.JTextField();
        labelRechercher = new javax.swing.JLabel();
        labelConteneurBas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAdminGen = new javax.swing.JTable();
        panelAjouter = new javax.swing.JPanel();
        textNomPharm = new javax.swing.JTextField();
        textAdressePharm = new javax.swing.JTextField();
        textNomGerant = new javax.swing.JTextField();
        textPrenomGerant = new javax.swing.JTextField();
        textTel = new javax.swing.JTextField();
        textMail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        boutonValider = new javax.swing.JButton();
        boutonFermer = new javax.swing.JButton();
        panelModifier = new javax.swing.JPanel();
        comboPharm = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        textNom = new javax.swing.JTextField();
        textAdresse = new javax.swing.JTextField();
        checkNom = new javax.swing.JCheckBox();
        checkAdresse = new javax.swing.JCheckBox();
        checkNomGer = new javax.swing.JCheckBox();
        textNomGer = new javax.swing.JTextField();
        checkPrenomGer = new javax.swing.JCheckBox();
        textPrenomGer = new javax.swing.JTextField();
        checkNumero = new javax.swing.JCheckBox();
        textNumero = new javax.swing.JTextField();
        checkEmail = new javax.swing.JCheckBox();
        textEmail = new javax.swing.JTextField();
        boutonModifier = new javax.swing.JButton();
        boutonAnnuler = new javax.swing.JButton();
        panelSupprimer = new javax.swing.JPanel();
        comboPharma = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        boutonSupprimer = new javax.swing.JButton();
        boutonAnnulSup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAdminGeneral.setBackground(new java.awt.Color(255, 255, 255));
        panelAdminGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHeader.setBackground(new java.awt.Color(255, 255, 255));
        panelHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLogoPharm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionpharmacie/phar.png"))); // NOI18N
        panelHeader.add(labelLogoPharm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 5, 162, 120));

        labelAjoutPharm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionpharmacie/ajouterPharm.png"))); // NOI18N
        labelAjoutPharm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAjoutPharmMouseClicked(evt);
            }
        });
        panelHeader.add(labelAjoutPharm, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, 120, 50));

        labelModifPharm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionpharmacie/modifierPharm.png"))); // NOI18N
        labelModifPharm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelModifPharmMouseClicked(evt);
            }
        });
        panelHeader.add(labelModifPharm, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 40, 120, 50));

        labelSupPharm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionpharmacie/supprimerPharm.png"))); // NOI18N
        labelSupPharm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSupPharmMouseClicked(evt);
            }
        });
        panelHeader.add(labelSupPharm, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 40, 120, 50));

        labelDeconPharm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionpharmacie/deconnecterPharm.png"))); // NOI18N
        labelDeconPharm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDeconPharmMouseClicked(evt);
            }
        });
        panelHeader.add(labelDeconPharm, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 40, 120, 50));

        labelConteneur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionpharmacie/conteneurPhar.png"))); // NOI18N
        panelHeader.add(labelConteneur, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 570, 90));

        panelAdminGeneral.add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 130));

        panelConsultation.setBackground(new java.awt.Color(255, 255, 255));
        panelConsultation.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));
        panelConsultation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textRechercher.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textRechercher.setForeground(new java.awt.Color(0, 102, 102));
        panelConsultation.add(textRechercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 260, 40));

        labelRechercher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionpharmacie/rechercher.png"))); // NOI18N
        labelRechercher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRechercherMouseClicked(evt);
            }
        });
        panelConsultation.add(labelRechercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 27, 150, 45));
        panelConsultation.add(labelConteneurBas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 770, 60));

        jScrollPane1.setBackground(new java.awt.Color(0, 204, 204));

        tableAdminGen.setBackground(new java.awt.Color(0, 204, 204));
        tableAdminGen.setForeground(new java.awt.Color(255, 255, 255));
        tableAdminGen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nom Pharmacie", "Adresse Pharmacie", "Nom gérant", "Prenom gérant", "numéro gérant"
            }
        ));
        tableAdminGen.setSelectionBackground(new java.awt.Color(0, 51, 51));
        tableAdminGen.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tableAdminGen);

        panelConsultation.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 550, 110));

        panelAdminGeneral.add(panelConsultation, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 1090, 230));

        panelAjouter.setBackground(new java.awt.Color(0, 204, 204));
        panelAjouter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textNomPharm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomPharmActionPerformed(evt);
            }
        });
        panelAjouter.add(textNomPharm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 250, 30));

        textAdressePharm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAdressePharmActionPerformed(evt);
            }
        });
        panelAjouter.add(textAdressePharm, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 250, 30));

        textNomGerant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomGerantActionPerformed(evt);
            }
        });
        panelAjouter.add(textNomGerant, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 250, 30));
        panelAjouter.add(textPrenomGerant, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 250, 30));

        textTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTelActionPerformed(evt);
            }
        });
        panelAjouter.add(textTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 250, 30));

        textMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMailActionPerformed(evt);
            }
        });
        panelAjouter.add(textMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 250, 30));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nom Pharmacie :");
        panelAjouter.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("adresse pharmacie :");
        panelAjouter.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" Nom Gerant :");
        panelAjouter.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Prenom Gerant :");
        panelAjouter.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("telephone :");
        panelAjouter.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email :");
        panelAjouter.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        boutonValider.setText("valider");
        boutonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonValiderActionPerformed(evt);
            }
        });
        panelAjouter.add(boutonValider, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 150, -1));

        boutonFermer.setText("fermer");
        boutonFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonFermerActionPerformed(evt);
            }
        });
        panelAjouter.add(boutonFermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 150, -1));

        panelAdminGeneral.add(panelAjouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 690, 300));

        panelModifier.setBackground(new java.awt.Color(0, 204, 204));
        panelModifier.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboPharm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelModifier.add(comboPharm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 250, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nom Pharmacie :");
        panelModifier.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        textNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomActionPerformed(evt);
            }
        });
        panelModifier.add(textNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 170, -1));
        panelModifier.add(textAdresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 190, -1));

        checkNom.setText("modifier nom Pharmacie");
        checkNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNomActionPerformed(evt);
            }
        });
        panelModifier.add(checkNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        checkAdresse.setText("modifier adresse Pharmacie");
        checkAdresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAdresseActionPerformed(evt);
            }
        });
        panelModifier.add(checkAdresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        checkNomGer.setText("modifier Nom Gerant");
        checkNomGer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNomGerActionPerformed(evt);
            }
        });
        panelModifier.add(checkNomGer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));
        panelModifier.add(textNomGer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 170, -1));

        checkPrenomGer.setText("modifier Prenom Gerant");
        checkPrenomGer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPrenomGerActionPerformed(evt);
            }
        });
        panelModifier.add(checkPrenomGer, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));
        panelModifier.add(textPrenomGer, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 190, -1));

        checkNumero.setText("modifier Numéro Gérant");
        checkNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNumeroActionPerformed(evt);
            }
        });
        panelModifier.add(checkNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));
        panelModifier.add(textNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 190, -1));

        checkEmail.setText("modifer email gerant");
        checkEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEmailActionPerformed(evt);
            }
        });
        panelModifier.add(checkEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));
        panelModifier.add(textEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 190, -1));

        boutonModifier.setText("modifier");
        boutonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonModifierActionPerformed(evt);
            }
        });
        panelModifier.add(boutonModifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 120, -1));

        boutonAnnuler.setText("annuler");
        boutonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAnnulerActionPerformed(evt);
            }
        });
        panelModifier.add(boutonAnnuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 130, -1));

        panelAdminGeneral.add(panelModifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 160, 700, 290));

        panelSupprimer.setBackground(new java.awt.Color(0, 204, 204));
        panelSupprimer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboPharma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelSupprimer.add(comboPharma, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 310, 40));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nom Pharmacie :");
        jLabel8.setToolTipText("");
        panelSupprimer.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        boutonSupprimer.setText("supprimer");
        boutonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonSupprimerActionPerformed(evt);
            }
        });
        panelSupprimer.add(boutonSupprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 170, 140, 40));

        boutonAnnulSup.setText("annuler");
        boutonAnnulSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAnnulSupActionPerformed(evt);
            }
        });
        panelSupprimer.add(boutonAnnulSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 150, 40));

        panelAdminGeneral.add(panelSupprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 550, 240));

        getContentPane().add(panelAdminGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNomGerantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomGerantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomGerantActionPerformed

    private void textMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMailActionPerformed

    private void textTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTelActionPerformed

    private void textAdressePharmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAdressePharmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAdressePharmActionPerformed

    private void textNomPharmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomPharmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomPharmActionPerformed

    private void labelAjoutPharmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAjoutPharmMouseClicked
        // TODO add your handling code here:
        panelAjouter.setVisible(true);
        panelModifier.setVisible(false);
        panelSupprimer.setVisible(false);
    }//GEN-LAST:event_labelAjoutPharmMouseClicked

    private void boutonFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonFermerActionPerformed
        // TODO add your handling code here:
        textNomPharm.setText("");
        textAdressePharm.setText("");
        textNomGerant.setText("");
        textPrenomGerant.setText("");
        textTel.setText("");
        textMail.setText("");
        panelAjouter.setVisible(false);
    }//GEN-LAST:event_boutonFermerActionPerformed

    private void boutonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonValiderActionPerformed
        // TODO add your handling code here:
        ListeFonctions fonctions = new ListeFonctions();
        String infos[] = {textNomPharm.getText(), textAdressePharm.getText(), textNomGerant.getText(), textPrenomGerant.getText(), textTel.getText(), textMail.getText()};
        boolean filled = fonctions.formulaireIsFilled(infos);
        if (filled == true) {
            boolean exist = fonctions.ifPharmExist(textNomPharm.getText());
            if (exist == false) {
                fonctions.ajouterPharmacie(textNomPharm.getText(), textAdressePharm.getText(), textNomGerant.getText(), textPrenomGerant.getText(), textTel.getText(), textMail.getText());
                JOptionPane.showMessageDialog(null, "La pharmacie '" + textNomPharm.getText() + "' a été bien ajoutée. \n Pour plus d'informations vous pouvez le vérifier dans la zone de recherche.");
            } else {
                JOptionPane.showMessageDialog(null, "Désolé mais le nom de pharmacie '" + textNomPharm.getText() + "' existe déjà.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Veuillez bien remplir le formulaire.");
        }
        textNomPharm.setText("");
        textAdressePharm.setText("");
        textNomGerant.setText("");
        textPrenomGerant.setText("");
        textTel.setText("");
        textMail.setText("");
    }//GEN-LAST:event_boutonValiderActionPerformed

    private void labelRechercherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRechercherMouseClicked
        // TODO add your handling code here:
        ListeFonctions fonctions = new ListeFonctions();
        String req = "";
        if (textRechercher.getText().equals("")) {
            req = "SELECT pharmacie_t.nom as c, adresse, gerant_t.prenom as a, gerant_t.nom as b, tel, email, id,mdp FROM pharmacie_t, gerant_t WHERE gerant_t.id = pharmacie_t.id_gerant ";
        } else {
            req = "SELECT pharmacie_t.nom as c, adresse, gerant_t.prenom as a, gerant_t.nom as b, tel, email, id,mdp FROM pharmacie_t, gerant_t WHERE pharmacie_t.nom LIKE \"" + textRechercher.getText() + "%\" AND pharmacie_t.id_gerant = gerant_t.id;";
        }
        ResultSet rs = fonctions.getData(req);
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("nom pharmacie");
        model.addColumn("adresse Pharmacie");
        model.addColumn("nomGerant");
        model.addColumn("prenom Gerant");
        model.addColumn("telephone");
        model.addColumn("email");
        model.addColumn("login");
        model.addColumn("password");
        try {
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString("c"), rs.getString("adresse"), rs.getString("a"), rs.getString("b"), rs.getString("tel"), rs.getString("email"), rs.getString("id"), rs.getString("mdp")});
            }
        } catch (SQLException ex) {
            System.err.println(ex);
        }
        tableAdminGen.setModel(model);
    }//GEN-LAST:event_labelRechercherMouseClicked

    private void textNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomActionPerformed

    private void checkNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNomActionPerformed
        // TODO add your handling code here:
        if (checkNom.isSelected()) {
            textNom.setVisible(true);
        } else {
            textNom.setVisible(false);
        }
    }//GEN-LAST:event_checkNomActionPerformed

    private void checkAdresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAdresseActionPerformed
        // TODO add your handling code here:
        if (checkAdresse.isSelected()) {
            textAdresse.setVisible(true);
        } else {
            textAdresse.setVisible(false);
        }
    }//GEN-LAST:event_checkAdresseActionPerformed

    private void checkNomGerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNomGerActionPerformed
        // TODO add your handling code here:
        if (checkNomGer.isSelected()) {
            textNomGer.setVisible(true);
        } else {
            textNomGer.setVisible(false);
        }
    }//GEN-LAST:event_checkNomGerActionPerformed

    private void checkPrenomGerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPrenomGerActionPerformed
        // TODO add your handling code here:
        if (checkPrenomGer.isSelected()) {
            textPrenomGer.setVisible(true);
        } else {
            textPrenomGer.setVisible(false);
        }
    }//GEN-LAST:event_checkPrenomGerActionPerformed

    private void checkNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNumeroActionPerformed
        // TODO add your handling code here:
        if (checkNumero.isSelected()) {
            textNumero.setVisible(true);
        } else {
            textNumero.setVisible(false);
        }
    }//GEN-LAST:event_checkNumeroActionPerformed

    private void checkEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEmailActionPerformed
        // TODO add your handling code here:
        if (checkEmail.isSelected()) {
            textEmail.setVisible(true);
        } else {
            textEmail.setVisible(false);
        }
    }//GEN-LAST:event_checkEmailActionPerformed

    private void boutonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAnnulerActionPerformed
        // TODO add your handling code here:
        checkAdresse.setSelected(false);
        textAdresse.setText("");
        textAdresse.setVisible(false);
        checkNom.setSelected(false);
        textNom.setText("");
        textNom.setVisible(false);
        checkNomGer.setSelected(false);
        textNomGer.setText("");
        textNomGer.setVisible(false);
        checkPrenomGer.setSelected(false);
        textPrenomGer.setText("");
        textPrenomGer.setVisible(false);
        checkNumero.setSelected(false);
        textNumero.setText("");
        textNumero.setVisible(false);
        checkEmail.setSelected(false);
        textEmail.setText("");
        textEmail.setVisible(false);
        panelModifier.setVisible(false);
    }//GEN-LAST:event_boutonAnnulerActionPerformed

    private void labelModifPharmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModifPharmMouseClicked
        // TODO add your handling code here:
        ListeFonctions fonctions = new ListeFonctions();
        String req = "SELECT nom FROM pharmacie_t;";
        ResultSet rs = fonctions.getData(req);
        String chaine = "nom";
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model = fonctions.chargerComboSingle(rs, chaine);
        comboPharm.setModel(model);
        panelModifier.setVisible(true);
        panelAjouter.setVisible(false);
        panelSupprimer.setVisible(false);

    }//GEN-LAST:event_labelModifPharmMouseClicked

    private void boutonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonModifierActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Debut de la fonction.");
        ListeFonctions fonctions = new ListeFonctions();
        String req;
        String tab[] = new String[7];
        int i = 0;
        boolean filled = false;
        boolean select = false;
        //enregistrement dans un tableau
        if (checkAdresse.isSelected()) {
            tab[i] = textAdresse.getText();
            i++;
            select = true;
        }
        if (checkNom.isSelected()) {
            tab[i] = textNom.getText();
            i++;
            select = true;
        }
        if (checkNomGer.isSelected()) {
            tab[i] = textNomGer.getText();
            i++;
            select = true;
        }
        if (checkPrenomGer.isSelected()) {
            tab[i] = textPrenomGer.getText();
            i++;
            select = true;
        }
        if (checkNumero.isSelected()) {
            tab[i] = textNumero.getText();
            i++;
            select = true;
        }
        if (checkEmail.isSelected()) {
            tab[i] = textEmail.getText();
            select = true;
        }
        filled = fonctions.formulaireIsFilled2(tab, i);
        JOptionPane.showMessageDialog(null, "filled = " + filled);
        if (filled == true && select == true) {
            //UPDATES

            if (checkAdresse.isSelected()) {
                req = "UPDATE pharmacie_t SET adresse = '" + textAdresse.getText() + "' WHERE nom = '" + comboPharm.getSelectedItem().toString() + "';";
                fonctions.setData(req);

            }
            if (checkNom.isSelected()) {
                boolean exist = fonctions.ifPharmExist(textNom.getText());
                if (exist == false) {
                    req = "UPDATE pharmacie_t SET nom = '" + textNom.getText() + "' WHERE nom = '" + comboPharm.getSelectedItem().toString() + "';";
                    fonctions.setData(req);
                    String request = "SELECT nom FROM pharmacie_t;";
                    ResultSet rs = fonctions.getData(request);
                    String chaine = "nom";
                    DefaultComboBoxModel model = new DefaultComboBoxModel();
                    model = fonctions.chargerComboSingle(rs, chaine);
                    comboPharm.setModel(model);
                } else {
                    JOptionPane.showMessageDialog(null, "Désolé ce nom de pharmacie existe déjà.");
                }

            }
            if (checkNomGer.isSelected()) {
                req = "UPDATE gerant_t SET nom = '" + textNomGer.getText() + "' WHERE id IN (SELECT id_gerant FROM pharmacie_t WHERE nom = '" + comboPharm.getSelectedItem().toString() + "');";
                fonctions.setData(req);
            }
            if (checkPrenomGer.isSelected()) {
                req = "UPDATE gerant_t SET prenom = '" + textPrenomGer.getText() + "' WHERE id IN (SELECT id_gerant FROM pharmacie_t WHERE nom = '" + comboPharm.getSelectedItem().toString() + "');";
                fonctions.setData(req);
            }
            if (checkNumero.isSelected()) {
                req = "UPDATE gerant_t SET tel = '" + textNumero.getText() + "' WHERE id IN (SELECT id_gerant FROM pharmacie_t WHERE nom = '" + comboPharm.getSelectedItem().toString() + "');";
                fonctions.setData(req);
            }
            if (checkEmail.isSelected()) {
                req = "UPDATE gerant_t SET email = '" + textEmail.getText() + "' WHERE id IN (SELECT id_gerant FROM pharmacie_t WHERE nom = '" + comboPharm.getSelectedItem().toString() + "');";
                fonctions.setData(req);
            }
            JOptionPane.showMessageDialog(null, "Vos données ont été modifiées.\n Vous pouvez le vérifier en dessous.");
            checkAdresse.setSelected(false);
            textAdresse.setText("");
            textAdresse.setVisible(false);
            checkNom.setSelected(false);
            textNom.setText("");
            textNom.setVisible(false);
            checkNomGer.setSelected(false);
            textNomGer.setText("");
            textNomGer.setVisible(false);
            checkPrenomGer.setSelected(false);
            textPrenomGer.setText("");
            textPrenomGer.setVisible(false);
            checkNumero.setSelected(false);
            textNumero.setText("");
            textNumero.setVisible(false);
            checkEmail.setSelected(false);
            textEmail.setText("");
            textEmail.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Veuillez bien remplir le formulaire.");
        }
    }//GEN-LAST:event_boutonModifierActionPerformed

    private void boutonAnnulSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAnnulSupActionPerformed
        // TODO add your handling code here:
        panelSupprimer.setVisible(false);
    }//GEN-LAST:event_boutonAnnulSupActionPerformed

    private void labelSupPharmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSupPharmMouseClicked
        // TODO add your handling code here:
        ListeFonctions fonctions = new ListeFonctions();
        String req = "SELECT nom FROM pharmacie_t;";
        ResultSet rs = fonctions.getData(req);
        String chaine = "nom";
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model = fonctions.chargerComboSingle(rs, chaine);
        comboPharma.setModel(model);
        panelModifier.setVisible(false);
        panelAjouter.setVisible(false);
        panelSupprimer.setVisible(true);
    }//GEN-LAST:event_labelSupPharmMouseClicked

    private void boutonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonSupprimerActionPerformed
        // TODO add your handling code here:
        ListeFonctions fonctions = new ListeFonctions();
        int reponse = JOptionPane.showConfirmDialog(null, "êtes-vous sûre de vouloir continuer.");
        if (reponse == 0) {

            String req = "DELETE FROM gerant_t WHERE id IN (SELECT id_gerant FROM pharmacie_t WHERE nom = '" + comboPharma.getSelectedItem().toString() + "');";
            fonctions.setData(req);
            req = "SELECT nom FROM pharmacie_t;";
            ResultSet rs = fonctions.getData(req);
            String chaine = "nom";
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            model = fonctions.chargerComboSingle(rs, chaine);
            comboPharma.setModel(model);

        }

    }//GEN-LAST:event_boutonSupprimerActionPerformed

    private void labelDeconPharmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDeconPharmMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_labelDeconPharmMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrateurGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrateurGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrateurGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrateurGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdministrateurGeneral adminGen = new AdministrateurGeneral();
                adminGen.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonAnnulSup;
    private javax.swing.JButton boutonAnnuler;
    private javax.swing.JButton boutonFermer;
    private javax.swing.JButton boutonModifier;
    private javax.swing.JButton boutonSupprimer;
    private javax.swing.JButton boutonValider;
    private javax.swing.JCheckBox checkAdresse;
    private javax.swing.JCheckBox checkEmail;
    private javax.swing.JCheckBox checkNom;
    private javax.swing.JCheckBox checkNomGer;
    private javax.swing.JCheckBox checkNumero;
    private javax.swing.JCheckBox checkPrenomGer;
    private javax.swing.JComboBox<String> comboPharm;
    private javax.swing.JComboBox<String> comboPharma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAjoutPharm;
    private javax.swing.JLabel labelConteneur;
    private javax.swing.JLabel labelConteneurBas;
    private javax.swing.JLabel labelDeconPharm;
    private javax.swing.JLabel labelLogoPharm;
    private javax.swing.JLabel labelModifPharm;
    private javax.swing.JLabel labelRechercher;
    private javax.swing.JLabel labelSupPharm;
    private javax.swing.JPanel panelAdminGeneral;
    private javax.swing.JPanel panelAjouter;
    private javax.swing.JPanel panelConsultation;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelModifier;
    private javax.swing.JPanel panelSupprimer;
    private javax.swing.JTable tableAdminGen;
    private javax.swing.JTextField textAdresse;
    private javax.swing.JTextField textAdressePharm;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textMail;
    private javax.swing.JTextField textNom;
    private javax.swing.JTextField textNomGer;
    private javax.swing.JTextField textNomGerant;
    private javax.swing.JTextField textNomPharm;
    private javax.swing.JTextField textNumero;
    private javax.swing.JTextField textPrenomGer;
    private javax.swing.JTextField textPrenomGerant;
    private javax.swing.JTextField textRechercher;
    private javax.swing.JTextField textTel;
    // End of variables declaration//GEN-END:variables
    private String loginConnecter;
    private String pwdConnecter;
}
